# Deep Learning Model
# All copyrights belongs to © Prakhar Dwivedi, Rishabh Kumar, Sagar Chandrekar, Madhav Krishna Vakka

### Importing the libraries

In [749]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [750]:
tf.__version__

'2.17.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [751]:
dataset = pd.read_excel('Rough.xlsx')
X = dataset.iloc[0:, :3].values
y = dataset.iloc[:, -1].values

In [752]:
print(X)

[[1.25e+03 3.00e+02 1.25e+00]
 [1.00e+03 3.75e+02 2.50e-01]
 [7.50e+02 6.00e+02 1.25e+00]
 [7.50e+02 3.00e+02 7.50e-01]
 [1.50e+03 3.75e+02 1.25e+00]
 [1.25e+03 4.50e+02 1.25e+00]
 [1.00e+03 3.00e+02 1.25e+00]
 [7.50e+02 1.50e+02 1.25e+00]
 [1.50e+03 6.00e+02 7.50e-01]
 [1.50e+03 4.50e+02 2.50e-01]
 [1.00e+03 4.50e+02 2.50e-01]
 [7.50e+02 3.75e+02 7.50e-01]
 [1.25e+03 6.00e+02 2.50e-01]
 [1.25e+03 2.25e+02 7.50e-01]
 [1.00e+03 1.50e+02 1.25e+00]
 [1.00e+03 3.00e+02 7.50e-01]
 [7.50e+02 4.50e+02 1.25e+00]
 [1.50e+03 6.00e+02 2.50e-01]
 [1.25e+03 5.25e+02 7.50e-01]]


In [753]:
print(y)

[2.4 2.6 4.4 2.6 2.5 2.3 2.3 1.9 2.6 3.2 4.  3.1 3.8 2.1 1.6 2.1 3.3 3.2
 2.5]


### Encoding categorical data

Label Encoding the "ToolUsed" column

In [754]:
'''from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])'''

'from sklearn.preprocessing import LabelEncoder\nle = LabelEncoder()\nX[:, 2] = le.fit_transform(X[:, 2])'

In [755]:
'''print(X)   # 1 -> Turning
           # 0 -> Knurling'''

'print(X)   # 1 -> Turning\n           # 0 -> Knurling'

One Hot Encoding the "Geography" column

In [756]:
'''from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))'''

"from sklearn.compose import ColumnTransformer\nfrom sklearn.preprocessing import OneHotEncoder\nct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')\nX = np.array(ct.fit_transform(X))"

In [757]:
'print(X)'

'print(X)'

### Splitting the dataset into the Training set and Test set

In [758]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.8, random_state = 0)

### Feature Scaling

In [759]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN - Core Component of Deep Learning

### Initializing the ANN

In [760]:
ann = tf.keras.models.Sequential()   # Making 'ann' variable into a object created from the instances of sequential class.

### Adding the input layer and the first hidden layer

In [761]:
ann.add(tf.keras.layers.Dense(units=6, activation= 'relu'))   # From 'ann' we are creating dancing class.

# units in Dense() class creates number of hidden layers of neurons into it.
# Activation function in hidden layers should be Rectifier Activation Function. i.e. 'relu'

### Adding the second hidden layer

In [762]:
ann.add(tf.keras.layers.Dense(units= 6, activation= 'relu'))

### Adding the third hidden layer

In [763]:
ann.add(tf.keras.layers.Dense(units=6, activation= 'relu'))

### Adding the fourth hidden layer

In [764]:
ann.add(tf.keras.layers.Dense(units=6, activation= 'relu'))

### Adding the fifth hidden layer

In [765]:
ann.add(tf.keras.layers.Dense(units=6, activation= 'relu'))

### Adding the sixth hidden layer

In [766]:
ann.add(tf.keras.layers.Dense(units=6, activation= 'relu'))

### Adding the seventh hidden layer

In [767]:
ann.add(tf.keras.layers.Dense(units=6, activation= 'relu'))

### Adding the output layer

In [768]:
ann.add(tf.keras.layers.Dense(units=1 ))    # This is output code. Since our output data is Binary hence 'units =1'

# If it was Classification Model (having multiple options as result we will use 'units =3' that too after one-hot encoding those outputs).

# In Output layer our 'activation function' would be 'sigmoid' because it gives result as well as probability.

## Part 3 - Training the ANN

### Compiling the ANN

In [769]:
ann.compile(optimizer = 'adam' , loss ='mean_squared_error')

### Training the ANN on the Training set

In [770]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 300)  # We are doing batch learning. epoch is learning strength

Epoch 1/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - loss: 8.2091
Epoch 2/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 8.2005
Epoch 3/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 8.1920
Epoch 4/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 8.1862
Epoch 5/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 8.1804
Epoch 6/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 8.1746
Epoch 7/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 8.1682
Epoch 8/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 8.1605
Epoch 9/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 8.1529
Epoch 10/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 8.1463
Epoch 11/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 8.1393
Epoch 12/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 8.1322
Epoch 13/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 8.1250
Epoch 14/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 8.1175
Epoch 15/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 8.1096
Epoch 16/300
1/1 ━━━━

## Part 4 - Making the predictions and evaluating the model

In [771]:
'''Prediciting The Surface Roughness Value'''


'Prediciting The Surface Roughness Value'

In [773]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
final = np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test),1)),1)
print(final)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
[[2.27 4.  ]
 [2.62 2.6 ]
 [2.71 2.6 ]
 [2.06 2.5 ]
 [2.61 1.6 ]
 [2.99 3.3 ]
 [2.34 2.3 ]
 [1.66 2.5 ]
 [2.19 4.4 ]
 [1.54 2.3 ]
 [2.2  2.1 ]
 [2.71 3.2 ]
 [2.86 1.9 ]
 [3.89 3.2 ]
 [3.27 3.1 ]
 [3.09 2.6 ]]


### Predicting the Test set results

### Making the Confusion Matrix